create table marks (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       subject varchar(1000) not null,
                       mark int not null,
                       student varchar(100) references students(diary_number),
                       mark_date_and_time timestamp
);